### ISSUE TITLE
Navigation to Edit Package

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb-ui#10]
Right now, the navigation to _Edit package (Paket bearbeiten)_ ist missing. It should be navigable in the list view Packages (8.3 Pakete) by clicking on the package name. Additionally, in other package list views (Regarding Providers, 8.9, 8.10) the navigation should be the same.

**Comment by dirk-ecker** [comment]
Please do not add multiple tasks into one ticket, otherwise this ticket will be open for a long time, since all tasks are solved.

The first step is done, we have a navigation possibility to edit a package without the dialog.
