### ISSUE TITLE
End-Datum in der Job-Liste

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb-ui#27]
In der Job-Liste auf der Startseite wird das End-Datum bei einem noch nicht beendeten Job mit 01.01.1970 angegeben.
Hier sollte besser kein Datum bzw. kein Eintrag zu sehen sein.

**Comment by hornmo** [comment]
Fixed in 6d0203a04d029e50225c92994fad6c85f5afede6
