### ISSUE TITLE
Einträge aus Job-Liste entfernen

### ISSUE THREAD

**Issue by philboeselager** [openlibraryenvironment/gokb-ui#29]
Im derzeitigen Stand sind die Einträge der Job-Liste zwar per Auswahlbox wählbar, jedoch lässt sich anschließend keine Aktion ausführen. Eine sinnvolle Aktion wäre (vermutlich), Einträge aus der Job-Liste zu entfernen. Eventuell können weitere Aktionen ergänzt werden.

**Comment by darupp** [comment]
Das könnte analog zu den anderen Listensichten aussehen:
  - Spalte mit "Papierkorb" zum Löschen eines Jobs
  - Button "Auswahl Löschen" oberhalb der Liste, die alle angehakten Jobs löscht. 

Problematisch sehe ich hier, dass ja nicht die Jobs gelöscht werden, sondern die Darstellung in der GUI - die Jobs existieren ja weiterhin. Insofern wäre eine Möglichkeit
  - Umbenennung von "Löschen" in "Ausblende"
  - Persistierung für diese Session in Cookie/Session
