### ISSUE TITLE
Automatisches Setzen der Kuratorengruppe

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb-ui#32]
Beim Anlegen eines Pakets oder Providers sollte die Kuratorengruppe automatisch gesetzt werden: 

Nutzer besitzt Admin-Rechte: bleibt wie gehabt

Nutzer besitzt keine Admin-Rechte: 
- Bei einer Kuratorengruppe des Nutzers: Automatisch diese Kuratorengruppe setzen. 
- Bei mehreren Kuratorengruppe des Nutzers: Die Auswahl unter "Hinzufügen" umfasst nur diejenigen Kuratorengruppen, in denen der Nutzer Mitglied ist.

**Comment by hornmo** [comment]
Fixed in 4544799588b86a660a8edbb749ada1f5fbbcf9bf.
