### ISSUE TITLE
Sammelticket kleine Auffälligkeiten

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb-ui#33]
- In den Dropdowns zu CuratoryGroups werden die Gruppen unabhängig vom Status angezeigt, also auch diejenigen, die "Deleted" sind. SOLL: Nur diejenigen mit Status "Current" werden angezeigt.
- Die Suche zur Verküpfung mit Anbietern und Plattformen in edit-package funktioniert nicht optimal. SOLL: 
   - Die Suche muss auch über Strings aus der Wortmitte funktionieren, also mit Rechts- und Linkstrunkierung. Beispielsweise muss ich über "springer" auch "Julius Springer Verlag" finden. (X) 
  - Bei Plattformen muss die Suche über Name und URL funktionieren. Im Idealfall sind die Treffer eingeschränkt auf die Plattformen des zuvor ausgewählten Anbieters.

Stand: 
- Weiterhin keine Phrasensuche möglich, sondern Stringsuche ("Georg Verlag" findet kein "Georg Thieme Verlag").
- Suche nach Alternate Names ist fraglich, da es dann viele unpräzise Treffer geben kann.
-

**Comment by hornmo** [comment]
Phrasensuche per ES in 35081b13536d736067d8062e548295bc521cf3c6.
