### ISSUE TITLE
Adding of Identifiers and Namespace integration - Package

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb-ui#4]
There should a consistent GUI function to add Identifiers througout the system. The concept lacks the problem of different namespaces. These should be integrated.

This applies to 
  * Create/Edit package (Concept 8.1, pp. 34; 8.2, pp.44f)

As general rule: Searching an Identifier should work *without* selecting a namespace. If multiple results are given, the user should see the warning message of Concept p. 39 (but including the different namespaces)

Where an Identifier is to be added, there should be a modal where you can
  * Select a namespace from a dropdwon
  * Enter an Identiefer as String
  * "Add" and "OK" Buttons

So there should be be functions to
  * GET all Identifier Namespaces from Backend
  * POST an Identifier, the Namespace (and the corresponding object reference) 

![addidentifier](https://user-images.githubusercontent.com/22748500/81171906-8c050c80-8f9d-11ea-8338-ab719b808c4f.png)

**Comment by philboeselager** [comment]
- Associated issue for Provider: #11 
- Associated issue for Titles: #12
