### ISSUE TITLE
In der Suche wird nach Klick auf "Zurücksetzen" der Suchbegriff auch in das ID-Feld kopiert

### ISSUE THREAD

**Issue by hemmefelix** [openlibraryenvironment/gokb-ui#41]
In der Suche nach

- [Paketen](https://gokb.org/gokb-ui/#/search-package)
- [Einzeltiteln](https://gokb.org/gokb-ui/#/search-title)
- [Anbietern](https://gokb.org/gokb-ui/#/search-provider)

wird der Suchterm aus dem Feld "Name" auch in das Feld "Identifikator" übertragen, sofern nach einer erfolgten Suche auf den Button "Zurücksetzen" geklickt wird. Der Button "Zurücksetzen" ist momentan ohne sichtbare Funktion.

**Schritte zum Reproduzieren:**

1. Login https://gokb.org/gokb-ui/#/search-package
2. Im Suchfeld "Name" den Suchbegriff `oxford` eintragen und die Suche abschicken
3. Den Button "Zurücksetzen" anklicken
4. Erneut in das Suchfeld "Name" klicken und an den bisherigen Suchbegriff `aaa` anfügen

**Ergebnis:**

- Nach Klick auf "Zurücksetzen" passiert nichts sichtbares in der UI.
- Text, der im Feld "Name" eingetragen wird, wird auch im Feld "Identifikator" gespiegelt und erzeugt deshalb nach Absenden der Anfrage 0 Treffer.
- Man kann die "Verknüpfung" zwischen beiden Feldern nur durch Neuladen der Seite lösen.

![image](https://user-images.githubusercontent.com/17432725/108700534-055af500-7507-11eb-9e9f-b4b169caf16c.png)

**Erwartetes Ergebnis:**

- Nach Klick auf "Zurücksetzen" werden alle Begriffe aus den Feldern entfernt und auch die Suchtreffer wieder zurückgesetzt.
- Text wird nicht zwischen den Suchfeldern geteilt.

**Comment by hornmo** [comment]
Fixed in 121520b672fe486b819bcf4ee6fb5dca41ac8bdd.
