### ISSUE TITLE
Search vs. create option - Provider

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb-ui#5]
At some views, the concept's search vs. create option is not implemented:

This applies to 
  * Create/Edit package: Add provider (Concept 8.1, pp. 35f. ; 8.2, p. 45)

In the concept, the default mode is a search mode. Only if the search gives no results, the additional create and edit fields are shown (See pp. 35f.)

I would recommend to implement the search mode first, as "Create package" and "Edit package" are usable this way. At a later point, the switch to create mode can be implemented.

### Recommended attributes to search in a search field

  * provider: name
  * platform: name
  * title: name

In a second step, it could be tested, if additional felds should be searched in the same or an extra search field

  * provider: name, variantNames, identifier
  * platform: name, variantNames, primaryURL
  * title: name, variantNames, identifier

**Comment by philboeselager** [comment]
- Associated issue for platform : #13
- Associated issue for package : #14
- Associated issue for titles : #15
