### ISSUE TITLE
Disable reviewer functionality temporarily - Package

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb-ui#7]
As the complete reviewer workflow has to be re-evaluated, this functionality should be disabled temporarily. Where you can choose a reviewer and enter a reviewing note, this should not be shown any more. _Review_ buttons that finish an operation like _Create Package_ should be changed to _OK_ Buttons or _Akzeptieren_ Buttons and not rely on the selection of a reviewer (as it is in the concept by selecting _Akzeptieren (ohne Review)_ shown on p. 60)

This applies to:
  * Create/Edit package (Concept 8.1, pp. 41f.; 8.2, p. 48)

**Comment by dirk-ecker** [comment]
Okay, removed from Package and Title, Provider not implemented so far.

**Comment by philboeselager** [comment]
Associated issues:

- Title: https://github.com/openlibraryenvironment/gokb-ui/issues/16
- Provider: https://github.com/openlibraryenvironment/gokb-ui/issues/17
