### ISSUE TITLE
Navigation to Create/Edit Provider

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb-ui#9]
In the concept, the navigation to _Create Provider (8.9 Provider anlegen)_ and _Edit Provider (8.10 Provider bearbeiten)_ is missing.

### Create Provider
  * Via list view _Provider (8.11 Provider suchen)_ there should be a list header button left to _Retire (Archivieren)_ with _Add (Hinzufügen)_ 
  * Additionaly, there should be a top level menue item _Create Provider (Provider anlegen)_ on the same level as _Create Package (Paket anlegen)_ and _Create Title (Einzeltitel anlegen)_

### Edit Provider
  * In the list view _Provider (8.11 Provider suchen)_ by clicking on the provider name

**Comment by dirk-ecker** [comment]
Same here. It is bad practice to describe multiple tasks in one ticket, please split it.

**Comment by dirk-ecker** [comment]
Button Add added to list view Provider
Top level menu item for Provider added.
Possibility to jump in edit mode for provider added.
